name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write
  deployments: write
  discussions: write
  statuses: write
  actions: write
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint # Ensure you have a lint script in package.json

    - name: Run tests
      run: npm test
